# Generated by Django 2.2.1 on 2019-06-04 09:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_auto_20190603_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='CourseRate',
        ),
    ]
